export const SET_APPLYCATIONS = 'SET_APPLYCATIONS'
export type SET_APPLYCATIONS_TYPE = typeof SET_APPLYCATIONS

export const RESET_SHORTCUTS = 'RESET_SHORTCUTS'
export type RESET_SHORTCUTS_TYPE = typeof RESET_SHORTCUTS
export const CHANGE_ENABLE_GLOBAL_SHORTCUT = 'CHANGE_ENABLE_GLOBAL_SHORTCUT'
export type CHANGE_ENABLE_GLOBAL_SHORTCUT_TYPE =
  typeof CHANGE_ENABLE_GLOBAL_SHORTCUT
export const UPDATE_SHORTCUT = 'UPDATE_SHORTCUT'
export type UPDATE_SHORTCUT_TYPE = typeof UPDATE_SHORTCUT

export enum Types {}
